python ./get_cau_maps.py -n machine-1-1.pkl
python ./get_cau_maps.py -n machine-1-2.pkl
python ./get_cau_maps.py -n machine-1-3.pkl
python ./get_cau_maps.py -n machine-1-4.pkl
python ./get_cau_maps.py -n machine-1-5.pkl
python ./get_cau_maps.py -n machine-1-6.pkl
python ./get_cau_maps.py -n machine-1-7.pkl
python ./get_cau_maps.py -n machine-1-8.pkl
python ./get_cau_maps.py -n machine-2-1.pkl
python ./get_cau_maps.py -n machine-2-2.pkl
python ./get_cau_maps.py -n machine-2-3.pkl
python ./get_cau_maps.py -n machine-2-4.pkl
python ./get_cau_maps.py -n machine-2-5.pkl
python ./get_cau_maps.py -n machine-2-6.pkl
python ./get_cau_maps.py -n machine-2-7.pkl
python ./get_cau_maps.py -n machine-2-8.pkl
python ./get_cau_maps.py -n machine-2-9.pkl
python ./get_cau_maps.py -n machine-3-1.pkl
python ./get_cau_maps.py -n machine-3-2.pkl
python ./get_cau_maps.py -n machine-3-3.pkl
python ./get_cau_maps.py -n machine-3-4.pkl
python ./get_cau_maps.py -n machine-3-5.pkl
python ./get_cau_maps.py -n machine-3-6.pkl
python ./get_cau_maps.py -n machine-3-7.pkl
python ./get_cau_maps.py -n machine-3-8.pkl
python ./get_cau_maps.py -n machine-3-9.pkl
python ./get_cau_maps.py -n machine-3-10.pkl
python ./get_cau_maps.py -n machine-3-11.pkl